export const FIND_ONE = 'DROPDOWN/FIND_ONE';
export const FIND_ONE_SUCCESS = 'DROPDOWN/FIND_ONE_SUCCESS';
export const FIND_ONE_FAILED = 'DROPDOWN/FIND_ONE_FAILED';
export const CREATE_ONE_SUCCESS = 'DROPDOWN/CREATE_ONE_SUCCESS';
