export const TOGGLE_NOTE_STREAM = 'LIST_PAGE/TOGGLE_NOTE_STREAM';
export const CLOSE_NOTE_STREAM = 'LIST_PAGE/CLOSE_NOTE_STREAM';
export const SET_NOTE_STREAM_PAGE = 'LIST_PAGE/SET_NOTE_STREAM_PAGE';
export const TOGGLE_DEV_EX_TOP_FILTER = 'LIST_PAGE/TOGGLE_DEV_EX_TOP_FILTER';
export const TOGGLE_DEV_EX_GROUPING = 'LIST_PAGE/TOGGLE_DEV_EX_GROUPING';
